ChunkedList: store pointers to next/last elements instead of indices …
ComputationalRadiationPhysics/redGrapes pull request #48
Opened 2023-12-12 13:25 UTC by michaelsippel

…to save overhead of address calculation and allow more efficient packing of ItemAccess

* this also reintroduces the chunk-size as template parameter instead of storing it as member
* initialize AtomicList with `chunk_capacity`, not allocation size
* AtomicList: construct Item/ItemControlBlock from `memory::Block`
* ChunkedList: construct Chunk from `memory::Block`
* reorder ChunkedList::Item struct for more efficient alignment
* encode `has_item` of ItemAccess into one 8-byte pointer using bitmagic

2023-12-12 13:29 UTC, michaelsippel commented
Here I'm still getting warnings which I dont understand

```
warning: 'short unsigned int __atomic_fetch_sub_2(volatile void*, short unsigned int, int)' writing 2 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]
  645 |       { return __atomic_fetch_sub(&_M_i, __i, int(__m)); }
```

2023-12-12 16:07 UTC, psychocoderHPC commented
> Here I'm still getting warnings which I dont understand
> 
> ```
> warning: 'short unsigned int __atomic_fetch_sub_2(volatile void*, short unsigned int, int)' writing 2 bytes into a region of size 0 overflows the destination [-Wstringop-overflow=]
>   645 |       { return __atomic_fetch_sub(&_M_i, __i, int(__m)); }
> ```

Could it be a hint that some data are unaligned?

2023-12-12 16:11 UTC, psychocoderHPC commented
@michaelsippel Is this PR a replacement for #45?

2023-12-12 16:34 UTC, psychocoderHPC requested changes
IMO we still have the double free issue I tried to solve with #45 and we have the problem that more than one thread can append a new chunk.

2023-12-12 16:34 UTC, psychocoderHPC commented on redGrapes/util/chunked_list.hpp
> +//#include <redGrapes/memory/bump_allocator.hpp>
?? why is this commented out?

2023-12-12 16:34 UTC, psychocoderHPC commented on redGrapes/util/chunked_list.hpp
> +            for( Item * item = first_item; item != last_item; item++ )
`last_item` is pointing by default to the element before the first item. If we never allocate memory but create a chunked_list does it mean we loop over non existing memory?

2023-12-12 16:34 UTC, psychocoderHPC commented on redGrapes/util/chunked_list.hpp
> +         * and the `has_element` bit in its MSB.
`MSB` ?? What is this?

2023-12-12 16:34 UTC, psychocoderHPC commented on redGrapes/util/chunked_list.hpp
> +            for( Item * item = first_item; item != last_item; item++ )
maybe `for( Item * item = first_item; item <= last_item ; item++ )`?

2023-12-12 16:34 UTC, psychocoderHPC commented on redGrapes/util/chunked_list.hpp
> +            chunks.erase( chunk );
If a thread is entering this line and at the same moment another thread is pushing an item and is increasing the counter and sees that no item is free and then releases the memory again we will have a double free.

2023-12-12 16:34 UTC, psychocoderHPC commented on redGrapes/util/chunked_list.hpp
>              auto prev_chunk = chunks.allocate_item();
How do we prevent that more than one thread is creating new memory?

2023-12-12 16:54 UTC, michaelsippel commented
Yes you are right, this PR does not include the fix for the double free yet ,  #45 is still neccesary, either one needs to be rebased

2023-12-12 17:01 UTC, michaelsippel commented on redGrapes/util/chunked_list.hpp
> +            chunks.erase( chunk );
in this version we increment item_count only after we are safe to have gotten a slot.  Only if the increment of `item_count` happens first and then decrements this is relevant

2023-12-12 17:02 UTC, michaelsippel commented on redGrapes/util/chunked_list.hpp
> +            for( Item * item = first_item; item != last_item; item++ )
True, currently this bug  doesnt manifest because a chunk is only allocated if at least one element exists , but when we switch to the algorithm where the thread with the last slot allocates the new chunk, it can happen that a chunk remains empty and thus creating an endless loop.

2023-12-12 17:04 UTC, michaelsippel commented on redGrapes/util/chunked_list.hpp
> +//#include <redGrapes/memory/bump_allocator.hpp>
commented because its not needed. Allocator is a template parameter. will be removed

2023-12-12 17:04 UTC, michaelsippel commented on redGrapes/util/chunked_list.hpp
> +         * and the `has_element` bit in its MSB.
MSB = most significant bit

2023-12-12 17:06 UTC, psychocoderHPC commented
I opened a PR against your PR to solve the double free and alloc issue: https://github.com/michaelsippel/redGrapes/pull/1
My local tests works well, please have a look

2023-12-12 17:07 UTC, psychocoderHPC commented on redGrapes/util/chunked_list.hpp
> +         * and the `has_element` bit in its MSB.
please add this to the first usage

2023-12-12 17:08 UTC, psychocoderHPC commented on redGrapes/util/chunked_list.hpp
> +//#include <redGrapes/memory/bump_allocator.hpp>
please remove the line.

2023-12-13 13:25 UTC, psychocoderHPC approved these changes

2023-12-13 13:26 UTC, merged