Task Template refactor
ComputationalRadiationPhysics/redGrapes pull request #58
Opened 2024-03-22 15:02 UTC by ikbuibui

Refactor RedGrapes away from macro based configuration, to using a templated task type
Change the init method
Move away from a lot of global variables
Fix the MPI example. MPI calls are now executed from the same thread
We can now have multiple thread pools/single threads with different kinds of workers
Bump to C++ 20 and start using concepts
A lot more

2024-03-26 13:35 UTC, psychocoderHPC requested changes

2024-03-26 13:35 UTC, psychocoderHPC commented on CMakeLists.txt
> +option(BUILD_TESTING "Build the tests")
Could you maybe add `... OFF)` so the reader do not know the defaults^^

2024-03-26 13:35 UTC, psychocoderHPC commented on CMakeLists.txt
> +option(BUILD_TESTING "Build the tests")
I am wondering if it is good practice to use the general CMake variable for testing, in cases where the user is using this header only library tests will be built if testing is e.g. enabled for the enduser application.

2024-03-26 13:35 UTC, psychocoderHPC commented on examples/1_resources.cpp
> +    using TTask = redGrapes::Task<>;
offline discussed: This should maybe moved after `init()` and than `rg.task()` should be called to work correctly even if MPI or CUDA extended the task signature.

2024-03-26 13:35 UTC, psychocoderHPC commented on examples/4_refinements.cpp
> +          [&]
We need to remember to add somewhere a document that it is fine to capture the readgrapes handle by reference into a task.

Maybe it is better in this lambda to write `[&rg]` to not capture other classes by accident.

2024-03-26 13:35 UTC, psychocoderHPC commented on examples/CMakeLists.txt
> +# if(LAPACK_FOUND AND LAPACKE_LIB)
why is this disabled?

2024-03-26 13:35 UTC, psychocoderHPC commented on examples/cholesky.cpp
> +    auto rg = rg::init(n_threads);
btw we have an object `rg` and a namespace `rg`. This could be confusing.

2024-03-26 13:35 UTC, psychocoderHPC commented on examples/cuda_mandelbrot.cu
> +    rg::init(rg::scheduler::make_tag_match_scheduler().add({}, pool_scheduler).add({SCHED_CUDA}, cuda_scheduler));
you ignored the return value but the function is defined with no discard so this line should throw warnings.
Please fix.

2024-03-26 13:35 UTC, psychocoderHPC commented on examples/cuda_mandelbrot.cu
> +    rg::init(rg::scheduler::make_tag_match_scheduler().add({}, pool_scheduler).add({SCHED_CUDA}, cuda_scheduler));
OK cuda is currently not running so this is not an issue.

2024-03-26 13:35 UTC, psychocoderHPC commented on examples/game_of_life.cpp
> +    using TaskType = decltype(rg)::RGTask;
Not required in this PR but the name should be `rg::Task` only. IMO no need to add RG into the task name since it is a class definition in a class.

2024-03-26 13:35 UTC, psychocoderHPC commented on examples/game_of_life.cpp
> +    // auto fr = rg.createFieldResource<Buffer>(); // wasteful
this should be removed if not needed.

2024-03-26 13:35 UTC, psychocoderHPC commented on examples/mpi.cpp
> +    using RGTask = redGrapes::Task<>;
This should be moved after `init()` else the task type will not contain MPI information or?
Is this a BUG?

2024-03-26 13:35 UTC, psychocoderHPC commented on examples/mpi.cpp
> +            // MPI_Init(nullptr, nullptr);
Where is the init now called?

2024-03-26 13:35 UTC, psychocoderHPC commented on redGrapes/dispatch/Worker.hpp
> +    // template<typename T, typename TTask>
WHy is this dead (commended out) code in here?

2024-03-26 13:35 UTC, psychocoderHPC commented on redGrapes/dispatch/Worker.hpp
> +        // readyQueue emplaceMentQueue notify?
dead code?

2024-03-26 13:35 UTC, psychocoderHPC commented on redGrapes/dispatch/mpi/mpiWorker.hpp
> +                // private:
dead code

2024-03-26 13:35 UTC, psychocoderHPC commented on redGrapes/dispatch/mpi/mpiWorker.hpp
> +                // private:
dead code?

2024-03-26 13:35 UTC, psychocoderHPC commented on redGrapes/dispatch/mpi/mpiWorker.hpp
> +                        // this->cv.wait(); // TODO fix this by fixing event_ptr notify to wake
dead code? Is this call not required?

2024-03-26 13:35 UTC, psychocoderHPC commented on redGrapes/dispatch/thread/WorkerThread.hpp
> +            /*
dead code?

2024-03-26 13:35 UTC, psychocoderHPC commented on redGrapes/dispatch/thread/DefaultWorker.tpp
> +/* Copyright 2020-2023 Michael Sippel
Your name is missing in all files you refactored.

2024-03-26 13:35 UTC, psychocoderHPC commented on redGrapes/redGrapes.hpp
> +            // TaskFreeCtx::next_worker % LocalImpl<RGTask>::worker_pool->size();
dead code?

2024-03-26 13:35 UTC, psychocoderHPC commented on redGrapes/redGrapes.hpp
> +// clang-format off
It is still required to disable formatting?
Maybe the code does not contain cyclic dependency anymore.

2024-03-26 13:35 UTC, psychocoderHPC commented on redGrapes/resource/resource.hpp
> +                    std::move(ResourceAccess<TTask>::AccessBase && other)) // TODO check this
BUG?? What should this code do?

2024-03-26 13:35 UTC, psychocoderHPC commented on redGrapes/resource/resource.hpp
> +                    std::move(ResourceAccess<TTask>::AccessBase && other)) // TODO check this
`std::move(static_cast<ResourceAccess<TTask>::AccessBase>(other))` ??

2024-03-26 13:35 UTC, psychocoderHPC commented on redGrapes/resource/resource.hpp
> +                    std::move(ResourceAccess<TTask>::AccessBase && other)) // TODO check this
`std::forward<ResourceAccess<TTask>::AccessBase>(other)` ??

2024-03-26 13:35 UTC, psychocoderHPC commented on redGrapes/sync/cv.hpp
> +        // std::atomic_flag busy;
dead code

2024-03-26 13:35 UTC, psychocoderHPC commented on redGrapes/task/future.hpp
> +    // void yield(scheduler::EventPtr event);
dead code

2024-03-26 13:35 UTC, psychocoderHPC commented on redGrapes/task/property/inherit.hpp
> +    // struct Task;
dead code

2024-03-26 13:35 UTC, psychocoderHPC commented on test/CMakeLists.txt
> +    # resource.cpp
why is this diabled

2024-03-26 13:35 UTC, psychocoderHPC commented on test/random_graph.cpp
> +    // rg::finalize();
dead code

2024-03-26 14:30 UTC, ikbuibui commented on examples/CMakeLists.txt
> +# if(LAPACK_FOUND AND LAPACKE_LIB)
Enabled

2024-03-26 14:40 UTC, ikbuibui commented on examples/4_refinements.cpp
> +          [&]
now capturing as [&rg], and added fixing the documentation to reflect this to my TODOs

2024-03-26 14:41 UTC, ikbuibui commented on examples/cholesky.cpp
> +    auto rg = rg::init(n_threads);
removed the rg namespace

2024-03-26 14:42 UTC, ikbuibui commented on examples/game_of_life.cpp
> +    // auto fr = rg.createFieldResource<Buffer>(); // wasteful
removed

2024-03-26 14:44 UTC, ikbuibui commented on examples/mpi.cpp
> +    using RGTask = redGrapes::Task<>;
this should be deduced from the init. Not a bug because MPI doesnt require any special task properties any more.

2024-03-26 14:44 UTC, ikbuibui commented on examples/1_resources.cpp
> +    using TTask = redGrapes::Task<>;
refactored

2024-03-26 14:51 UTC, ikbuibui commented on redGrapes/dispatch/mpi/mpiWorker.hpp
> +                        // this->cv.wait(); // TODO fix this by fixing event_ptr notify to wake
The MPI worker currently does the polling in a hot loop. Say if there is an Async MPI send-recieve pair, on the current rank redGrapes will execute these tasks and then poll thir requests for completion, however the other MPI rank with mathcing calls may be far behind this rank. If the MPI thread goes to sleep after polling for some time, there is no way to wake it anymore when the other MPI rank finally reaches the matching send-recieve.
The MPI worker can possibly go to sleep if the requestPool is empty and this is something I need to think and implement.

2024-03-26 14:51 UTC, ikbuibui commented on redGrapes/dispatch/mpi/mpiWorker.hpp
> +                        // this->cv.wait(); // TODO fix this by fixing event_ptr notify to wake
So I have left this as a todo and some dead code

2024-03-26 14:54 UTC, ikbuibui commented on redGrapes/dispatch/thread/WorkerThread.hpp
> +            /*
removed

2024-03-26 14:56 UTC, ikbuibui commented on redGrapes/dispatch/mpi/mpiWorker.hpp
> +                // private:
removed

2024-03-26 14:57 UTC, ikbuibui commented on redGrapes/dispatch/mpi/mpiWorker.hpp
> +                // private:
removed

2024-03-26 14:59 UTC, ikbuibui commented on redGrapes/dispatch/Worker.hpp
> +    // template<typename T, typename TTask>
Removed this whole file from the PR as it was initial work on Worker abstractions which is not included yet

2024-03-26 15:02 UTC, ikbuibui commented on redGrapes/resource/resource.hpp
> +                    std::move(ResourceAccess<TTask>::AccessBase && other)) // TODO check this
now using std::forward

2024-03-26 15:03 UTC, ikbuibui commented on redGrapes/sync/cv.hpp
> +        // std::atomic_flag busy;
Removed

2024-03-26 15:03 UTC, ikbuibui commented on redGrapes/task/property/inherit.hpp
> +    // struct Task;
removed

2024-03-26 15:04 UTC, ikbuibui commented on redGrapes/task/future.hpp
> +    // void yield(scheduler::EventPtr event);
removed

2024-03-26 15:06 UTC, ikbuibui commented on redGrapes/redGrapes.hpp
> +            // TaskFreeCtx::next_worker % LocalImpl<RGTask>::worker_pool->size();
Yes, added to my TODO to maybe implement different strategies to select next worker in the pool to which the task should be emplaced to. Currently doing a linear round robin assignment.
Dead code removed

2024-03-26 15:08 UTC, ikbuibui commented on test/random_graph.cpp
> +    // rg::finalize();
removed

2024-03-26 15:10 UTC, ikbuibui commented on CMakeLists.txt
> +option(BUILD_TESTING "Build the tests")
As discussed offline, maybe using a flag like redGrapes_TESTING is a good idea.
Postponing this to the future me.

2024-03-26 15:17 UTC, ikbuibui commented on examples/mpi.cpp
> +    using RGTask = redGrapes::Task<>;
So there is a problem and a source of bugs here. As anrgument to init, the user says which schedulers they would like, but the scheduler is templated on the task type. So, the user needs to define the Task type before init.
This can lead to a case where if the user calls `init<TaskType1>(Scheduler<TaskType2>)` which can happen easily because init will fall back to an empty Task type if none is specified, which might not be the same as the TaskType2. This will lead to ugly template errors.

2024-03-26 15:20 UTC, ikbuibui commented on examples/mpi.cpp
> +            // MPI_Init(nullptr, nullptr);
Init is called as `MPI_Init_thread(nullptr, nullptr, MPI_THREAD_FUNNELED, &prov);` 2 lines above. This should be the correct way of initializing MPI. 
Removed the dead init code.

2024-03-26 15:26 UTC, ikbuibui commented on redGrapes/dispatch/thread/DefaultWorker.tpp
> +/* Copyright 2020-2023 Michael Sippel
Added

2024-03-26 16:38 UTC, ikbuibui commented on redGrapes/redGrapes.hpp
> +// clang-format off
No more cyclic dependncies. Removed disable formatting. I should work on cleaning these up in a follow up PR

2024-03-26 16:49 UTC, ikbuibui commented on test/CMakeLists.txt
> +    # resource.cpp
enabled all tests

2024-03-27 13:27 UTC, michaelsippel reviewed
Just some thoughts pointing out some potential issues but despite them i am not against these changes.
In general I get the reasoning that having a template-based configuration is much better than preprocessor and additionally using a scoped `redGrapes` object to get rid of `finalize()` is a good thing.
However: this object needs to be passed around, requiring an additional reference which needs to be captured in every task-functor, which imho creates two potential problems:
1. Using [&] in all lambdas should be considered bad practice when writing redGrapes applications since this makes is *very easy* to introduce race conditions or lifetime issues. It is much safer to write out all capture-by-references explicitly.  Requiring to capture the redGrapes-context in each task therefore degrades usability.
2. It increases the size of each task by another 8-bytes to store the reference. Having a singleton is more efficient from this perspective, as we have seen that the memory-footprint of tasks is crucial for cache-utilization and thus overall performance.

Further, I saw that we now add another reference to the scheduler-object in each task , bloating the task-struct even more.    But thats fine for now, since we could probably optimize this later by using an 8-bit Index instead and storing the references to the scheduler objects in a global map.




At least on my system, the examples  `1_resources` , `4_refinements`, `game_of_life` and `mpi` all fail to compile with the following error:

```
redGrapes/redGrapes/resource/access/area.hpp:75:25: error: call of overloaded 'format_to(fmt::v10::basic_format_context<fmt::v10::appender, char>::iterator, const char [46], const std::array<long unsigned int, 2>::value_type&, const std::array<long unsigned int, 2>::value_type&)' is ambiguous
   75 |         return format_to(ctx.out(), "{{ \"area\" : {{ \"begin\" : {}, \"end\" : {} }} }}", acc[0], acc[1]);
```




To clarify:

> `Fix the MPI example. MPI calls are now executed from the same thread`
* The old version did already execute MPI tasks on the main thread. (`execute_task` called in `idle` function of the main-thread)
* If `MPI_Init_thread()` is used insted of `MPI_Init()` , it should be allowed by the MPI-Spec to use MPI-calls from any thread.
* Nevertheless, having a dedicated `MPIWorker` class much better!

2024-03-27 13:27 UTC, michaelsippel commented on redGrapes/task/task_builder.hpp
> -            build_helper.foo();
the call to `foo()` was a workaround for nvcc. Have you tested nvcc already to be sure it is not required anymore?

2024-03-27 13:27 UTC, michaelsippel commented on examples/mpi.cpp
> +#define ENABLE_WORKSTEALING 1
`#define ENABLE_WORKSTEALING` should probably be set before the includes

2024-03-27 13:27 UTC, michaelsippel commented on redGrapes/scheduler/thread_scheduler.hpp
> +            CondVar cv;
missing `#include "redGrapes/sync/cv.hpp"`

2024-03-27 13:27 UTC, michaelsippel commented on redGrapes/dispatch/thread/cpuset.hpp
this is probably dead code anyway since pinning is handled entirely by hwloc, right?

2024-03-27 15:04 UTC, ikbuibui commented on redGrapes/dispatch/thread/cpuset.hpp
Yes, removed the file

2024-03-27 15:04 UTC, ikbuibui commented on redGrapes/scheduler/thread_scheduler.hpp
> +            CondVar cv;
added

2024-03-27 15:04 UTC, ikbuibui commented on examples/mpi.cpp
> +#define ENABLE_WORKSTEALING 1
moved

2024-03-27 15:05 UTC, ikbuibui commented on redGrapes/task/task_builder.hpp
> -            build_helper.foo();
No I havent and I had no idea it was a workaround. Thanks for pointing that out. I will check it

2024-03-27 15:34 UTC, ikbuibui commented on redGrapes/task/task_builder.hpp
> -            build_helper.foo();
Seems to not be necessary with CUDA 12.0

2024-03-27 15:41 UTC, michaelsippel commented on redGrapes/task/task_builder.hpp
> -            build_helper.foo();
sorry that I forgot to add a comment in the code :|

2024-03-27 15:51 UTC, ikbuibui commented
>     1. Using [&] in all lambdas should be considered bad practice when writing redGrapes applications since this makes is _very easy_ to introduce race conditions or lifetime issues. It is much safer to write out all capture-by-references explicitly.  Requiring to capture the redGrapes-context in each task therefore degrades usability.

Yes, the capture by reference of the "redGrapes-context" should be done explicitly. However it currently isn't strictly required to capture it in each task, only in task which need to access methods in the redGrapes class inside the task from the user side, like emplace (for child tasks), scope_depth,  create_event etc.
>     2. It increases the size of each task by another 8-bytes to store the reference. Having a singleton is more efficient from this perspective, as we have seen that the memory-footprint of tasks is crucial for cache-utilization and thus overall performance.
I haven't profiled the code yet, so I appreciate this insight.

> Further, I saw that we now add another reference to the scheduler-object in each task , bloating the task-struct even more. But thats fine for now, since we could probably optimize this later by using an 8-bit Index instead and storing the references to the scheduler objects in a global map.

That is a good point and I also dislike storing the reference to the scheduler in the task. I was thinking of storing the scheduler information only as a type with the task. But this leads to some other complications so I havent decided on a way forward yet. Thanks for the suggesion

> At least on my system, the examples `1_resources` , `4_refinements`, `game_of_life` and `mpi` all fail to compile with the following error:
> 
> ```
> redGrapes/redGrapes/resource/access/area.hpp:75:25: error: call of overloaded 'format_to(fmt::v10::basic_format_context<fmt::v10::appender, char>::iterator, const char [46], const std::array<long unsigned int, 2>::value_type&, const std::array<long unsigned int, 2>::value_type&)' is ambiguous
>    75 |         return format_to(ctx.out(), "{{ \"area\" : {{ \"begin\" : {}, \"end\" : {} }} }}", acc[0], acc[1]);
> ```
Thanks for the report. I was able to reproduce it with clang. Will fix it.

2024-03-28 15:34 UTC, ikbuibui commented
Implemented changes and bumped minor version of RedGrapes

2024-04-02 13:04 UTC, michaelsippel commented on redGrapes/dispatch/mpi/mpiWorker.hpp
> +                        // this->cv.wait(); // TODO fix this by fixing event_ptr notify to wake
> The MPI worker can possibly go to sleep if the requestPool is empty and this is something I need to think and implement.

Agree. I'd say its a sufficient condition to check `request_pool.requests.empty()`.

2024-04-02 13:24 UTC, michaelsippel approved these changes

2024-04-05 07:09 UTC, michaelsippel commented
Is @psychocoderHPC fine with the updated changes?

2024-04-05 08:27 UTC, ikbuibui commented
> Is @psychocoderHPC fine with the updated changes?

Broadly yes, he will review the updates next week before merging.

2024-04-15 08:56 UTC, psychocoderHPC approved these changes

2024-04-15 08:56 UTC, merged